### ISSUE TITLE
Won't build on npm v1.4..28 and node v0.10.40

### ISSUE THREAD

**Issue by scottste** [golyakov/highstock-browserify#4]
When building on npm v1.4..28 and node v0.10.40 we get the following error:

npm ERR! not a package /var/folders/5f/c5b5cq0x4_n86vpj1t22htzc0000gp/T/npm-90627-2kk1VUNp/github.com/highslide-software/highstock-release.git
npm ERR! Error: ENOENT, open '/var/folders/5f/c5b5cq0x4_n86vpj1t22htzc0000gp/T/npm-90627-2kk1VUNp/github.com/highslide-software/highstock-release.git-unpack/package.json'

Changing the highstock-release dependency to "highstock-release": "git://github.com/highslide-software/highstock-release.git#v2.1.6" seems to resolve the issue.

**Comment by golyakov** [comment]
Fixed in version 1.0.6

**Comment by scottste** [comment]
Have you pushed the 1.0.6 version to master? The package.json is still showing 1.0.5 and I don't see any updates.

**Comment by golyakov** [comment]
Version 1.0.6 has been deployed in npm. Now I also pushed version 1.0.6 on github.
